%  This script opens yes, no files
%  It will plot and play each sound, pausing until you hit a key
%  between each play.

yes = {'y01.wav', ...
             'y02.wav', ...
             'y06.wav', ...
             'y07.wav', ...
             'y09.wav', ...
             'y10.wav', ...
             'y11.wav', ...
             'y21.wav', ...
             'y22.wav', ...
             'y23.wav', ...
             'y24.wav', ...
             'y33.wav'};

no = {'n01.wav', ...
             'n02.wav', ...
             'n11.wav', ...
             'n12.wav', ...
             'n13.wav', ...
             'n20.wav', ...
             'n21.wav', ...
             'n22.wav', ...
             'n28.wav', ...
             'n29.wav', ...
             'n30.wav', ...
             'n33.wav'};
                  

for k=1:length(yes)
    [seg,fs] = audioread(yes{k});
    soundsc(seg,fs)
    plot(seg)
    title('Yes')
    pause
end

for k=1:length(no)
    [seg,fs] = audioread(no{k});
    soundsc(seg,fs)
    plot(seg)
    title('No')
    pause
end

