% ee513 hw7
% problem 7.1
% matt ruffner
% Spring 2017

% this script plots the spectrogram of sample recordings in the 

testdir='yesnotest/';


yes = {'y01.wav', ...
             'y02.wav', ...
             'y06.wav', ...
             'y07.wav', ...
             'y09.wav', ...
             'y10.wav', ...
             'y11.wav', ...
             'y21.wav', ...
             'y22.wav', ...
             'y23.wav', ...
             'y24.wav', ...
             'y33.wav'};

no = {'n01.wav', ...
             'n02.wav', ...
             'n11.wav', ...
             'n12.wav', ...
             'n13.wav', ...
             'n20.wav', ...
             'n21.wav', ...
             'n22.wav', ...
             'n28.wav', ...
             'n29.wav', ...
             'n30.wav', ...
             'n33.wav'};
                  

for k=1:length(yes)
    [seg,fs] = audioread(strcat(testdir,yes{k}));
    soundsc(seg,fs)
    
    spectrogram(seg,kaiser(256,5),128,1024,fs,'yaxis')
    
    title('Yes')
    pause
end

for k=1:length(no)
    [seg,fs] = audioread(strcat(testdir,no{k}));
    soundsc(seg,fs)
    
    spectrogram(seg,kaiser(256,5),128,1024,fs,'yaxis')
    
    %plot(seg)
    title('No')
    pause
end