% ee513 hw7
% problem 3 test of written function
% estimating formant freqs
clear
testdir='yesnotest/';
yes = {'y01.wav', ...
             'y02.wav', ...
             'y03.wav', ...
             'y04.wav', ...
             'y05.wav', ...
             'y06.wav', ...
             'y07.wav', ...
             'y08.wav', ...
             'y09.wav', ...
             'y10.wav', ...
             'y11.wav', ...
             'y21.wav', ...
             'y22.wav', ...
             'y23.wav', ...
             'y24.wav', ...
             'y25.wav', ...
             'y26.wav', ...
             'y27.wav', ...
             'y28.wav', ...
             'y29.wav', ...
             'y30.wav', ...
             'y31.wav', ...
             'y32.wav', ...
             'y33.wav'};
no = {'n01.wav', ...
             'n02.wav', ...
             'n03.wav', ...
             'n04.wav', ...
             'n05.wav', ...
             'n06.wav', ...
             'n07.wav', ...
             'n08.wav', ...
             'n09.wav', ...
             'n10.wav', ...
             'n11.wav', ...
             'n12.wav', ...
             'n13.wav', ...
             'n20.wav', ...
             'n21.wav', ...
             'n22.wav', ...
             'n28.wav', ...
             'n29.wav', ...
             'n30.wav', ...
             'n33.wav'};

noforms=[];
yesforms=[];

for k=1:length(yes)
    [seg,fs] = audioread(strcat(testdir,yes{k}));
    
    seg = extractUtterance(seg,fs);
    
    forms = estFormants(seg,fs);
    
    % entries in each row are the ratio of the second formant to the fourth
    % formant frequency for both the first and second halves of the spoken
    % word
    
    yesforms=[yesforms; log(forms(2,1)/forms(4,1)),log(forms(2,2)/forms(4,2))];
end
 
for k=1:length(no)
    [seg,fs] = audioread(strcat(testdir,no{k}));
    
    seg = extractUtterance(seg,fs);
    
    forms = estFormants(seg,fs);
    
    % entries in each row are the ratio of the second formant to the fourth
    % formant frequency for both the first and second halves of the spoken
    % word
    noforms=[noforms; log(forms(2,1)/forms(4,1)),log(forms(2,2)/forms(4,2))];
end

figure(1)
hold on
plot(yesforms(:,1),yesforms(:,2),'go')
plot(noforms(:,1),noforms(:,2),'rx')
xlabel('dB Ratio of 2nd Formant to 4th Formant Frequency in the First Half of the Word')
ylabel('db Ratio of 2nd Formant to 4th Formant Frequency in the Second Half of the Word')
legend('Spoken "yes"','Spoken "no"')


